### PR TITLE
feat(front-end): analytics Page

### PR DESCRIPTION
**Pull request by Belgudei655**
Fix sidebar, analytics button, and route #84

### CODE REVIEW

**Review by Tugsjargal338 — APPROVED** [review]
GJ

**Review by AnandOchir — CHANGES_REQUESTED** [review]
ss 2024-04-09 at 13 19 19

Import deer darhaar settings huudasruu yvahad side bar deer settings huudas ni hightlight hiihgui bn

**Review by Enkhtaivan1 — CHANGES_REQUESTED** [review]
1. Side bar delgeegui uydee heterhii urgun baina uur platformuudaas sanaa avaad ch ymu argal design deereech tiim bish bga bh
2. Side bar delgetsen bh uydee heterhii nariihan buyu urgun n baga baina (width)
3. analytics page deer yagaad door n margin bgad bgag oilgohgu bn za zasaad yvuulaarai 


GL

**Review by Enkhtaivan1 — CHANGES_REQUESTED** [review]
Side bar

**Review by Tugsjargal338 — DISMISSED** [review]
WD

**Review by Enkhtaivan1 — CHANGES_REQUESTED** [review]
Sidebar delgegdsen bolgon delgegdeegui bh n hoorondoo adilhan bairlaltai baimaar bn delgeheer glitchy ym n dooshlood bga ymshig haragdaad bn

**Review by Enkhtaivan1 — CHANGES_REQUESTED** [review]
Sidebar icon uud delgegdeh uyde bariandaa thde hoiguur n text n orj ireh ystoi.

**Review by Enkhtaivan1 — APPROVED** [review]
lgtm

**Review by AnandOchir — APPROVED** [review]

**Pull request merged**
